version: '3.3'

services:
  # Postgres
  db:
    container_name: db
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pgcontrol
    ports:
      - "5430:5430"
    networks:
      - postgres-compose-network
    volumes:
      - ./database:/var/lib/postgresql/data

  web:
    container_name: py-control-ts
    build: .
    restart: always
    command: sh -c "python manage.py runserver 0.0.0.0:8001"
    networks:
      - postgres-compose-network
    volumes:
      - .:/webapps
    ports:
      - "8001:8001"
    links:
      - db
    depends_on:
      - db

networks: 
  postgres-compose-network:
    driver: bridge
