# Generated by Django 2.2.2 on 2020-12-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(blank=True, choices=[('Cadastros', 'Cadastros'), ('Movimentos', 'Movimentos'), ('Consultas', 'Consultas'), ('Relatórios', 'Relatórios'), ('Ferramentas', 'Ferramentas'), ('Outros', 'Outros')], default='Outros', max_length=20, null=True, verbose_name='Menu')),
                ('name', models.CharField(max_length=80, verbose_name='Módulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('date_update', models.DateField(auto_now=True, null=True, verbose_name='Emissão')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['name'],
            },
        ),
    ]
