# Generated by Django 2.2.2 on 2020-12-21 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 13, 42, 2, 668540, tzinfo=utc), null=True, verbose_name='Atualizada'),
        ),
    ]
