# Generated by Django 2.2.2 on 2020-12-21 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_modules_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='date_create',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Atualizada'),
        ),
    ]
