# Generated by Django 2.2.2 on 2021-01-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['companie__nickname', 'bank'], 'verbose_name': 'Remessa Bancária', 'verbose_name_plural': 'Remessas Bancárias'},
        ),
    ]
