# Generated by Django 2.2.2 on 2021-01-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210105_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.CharField(blank=True, choices=[('Banco do Brasil - 001', 'Banco do Brasil - 001'), ('Banrisul - 041', 'Banrisul - 041'), ('CEF - 104', 'CEF - 104'), ('Itáu - 341', 'Itáu - 341'), ('Santander - 033', 'Santander - 033'), ('Sicredi - 748', 'Sicredi - 748')], default='Outros', max_length=100, null=True, verbose_name='Banco'),
        ),
    ]
