# Generated by Django 2.2.2 on 2021-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20210105_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='date_update',
            field=models.DateField(blank=True, null=True, verbose_name='Cadastro'),
        ),
    ]
