# Generated by Django 2.2.2 on 2021-01-05 21:06

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0004_auto_20210105_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='user_create',
            field=models.ForeignKey(default=1, on_delete=False, related_name='user_bank', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='date_create',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Últ/Verificação'),
        ),
    ]
