# Generated by Django 2.2.2 on 2021-01-06 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_bank_date_inactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cadastro'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='date_update',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Últ/Verificação'),
        ),
    ]
