# Generated by Django 2.2.2 on 2021-01-06 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20210105_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='date_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Últ/Verificação'),
        ),
    ]
