# Generated by Django 2.2.2 on 2020-12-21 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_auto_20201204_1152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistem_operation', models.CharField(blank=True, choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('Outros', 'Outros')], default='Linux', max_length=20, null=True, verbose_name='S.O')),
                ('date_update', models.DateField(auto_now=True, null=True, verbose_name='Emissão')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('specification', models.TextField(verbose_name='Processo')),
                ('companie', models.ForeignKey(on_delete=False, related_name='empresa_routine', to='companies.Companies', verbose_name='Empresa')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=False, related_name='User_routine', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Rotina - Suporte',
                'verbose_name_plural': 'Rotinas - Suporte',
                'ordering': ['title'],
            },
        ),
    ]
