# Generated by Django 2.2.2 on 2020-12-23 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 23, 19, 4, 55, 994851, tzinfo=utc), null=True, verbose_name='Atualizada'),
        ),
    ]
