# Generated by Django 2.2.2 on 2020-12-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servers',
            name='description',
        ),
        migrations.AddField(
            model_name='servers',
            name='memory_ram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Memória RAM'),
        ),
        migrations.AddField(
            model_name='servers',
            name='processor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Processador'),
        ),
    ]
