# Generated by Django 2.2.2 on 2020-12-07 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0002_auto_20201207_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='database_definition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Definição do Banco de Dados'),
        ),
        migrations.AddField(
            model_name='servers',
            name='ip_network',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='servers',
            name='last_verification',
            field=models.DateField(blank=True, null=True, verbose_name='Data Última Verificação'),
        ),
        migrations.AddField(
            model_name='servers',
            name='partition_size_specification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Partições/tamanho'),
        ),
        migrations.AddField(
            model_name='servers',
            name='passwd_sistem_operation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Senha(S.O)'),
        ),
        migrations.AddField(
            model_name='servers',
            name='sistem_operation',
            field=models.CharField(blank=True, choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('Não especificado', 'Não especificado')], default='Linux', max_length=20, null=True, verbose_name='Sistema Operacional'),
        ),
        migrations.AddField(
            model_name='servers',
            name='sistem_specification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Especificação(S.O)'),
        ),
        migrations.AddField(
            model_name='servers',
            name='user_sistem_operation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuário(S.O)'),
        ),
        migrations.AddField(
            model_name='servers',
            name='user_verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Útima Verificação'),
        ),
    ]
