# Generated by Django 2.2.2 on 2020-12-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20201207_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='database_version',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Versão do Banco'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='database_definition',
            field=models.CharField(blank=True, choices=[('PosgreSQL', 'Linux'), ('Outros', 'Outros')], default='Linux', max_length=20, null=True, verbose_name='Banco de Dados'),
        ),
    ]
