# Generated by Django 2.2.2 on 2020-12-08 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0005_auto_20201207_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servers',
            options={'ordering': ['companie'], 'verbose_name': 'Servidor', 'verbose_name_plural': 'Servidores'},
        ),
        migrations.AlterField(
            model_name='servers',
            name='database_version',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='last_verification',
            field=models.DateField(blank=True, null=True, verbose_name='Última Verificação'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='memory_ram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='partition_size_specification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Partições/Tamanho'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='sistem_operation',
            field=models.CharField(blank=True, choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('Outros', 'Outros')], default='Linux', max_length=20, null=True, verbose_name='S.O'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='user_verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=50, verbose_name='Name do Banco')),
                ('database_size', models.IntegerField(blank=True, null=True, verbose_name='Tam. Banco(DB)')),
                ('hd_size_one', models.IntegerField(blank=True, null=True, verbose_name='Tam. Disco(SO)')),
                ('hd_size_two', models.IntegerField(blank=True, null=True, verbose_name='Tam. Disco(BD)')),
                ('last_verification', models.DateField(blank=True, null=True, verbose_name='Última Verificação')),
                ('server', models.ForeignKey(on_delete=False, related_name='server_info', to='servers.Servers', verbose_name='Servidor')),
                ('user_verification', models.ForeignKey(blank=True, null=True, on_delete=False, related_name='user_server', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Servidor - Monitoramento',
                'verbose_name_plural': 'Servidores - Monitoramento',
                'ordering': ['-last_verification'],
            },
        ),
    ]
