# Generated by Django 2.2.2 on 2020-12-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_auto_20201208_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='database_size_initials',
            field=models.CharField(blank=True, default='GB', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='hd_size_one_available_initials',
            field=models.CharField(blank=True, default='GB', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='hd_size_one_initials',
            field=models.CharField(blank=True, default='GB', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='hd_size_two_available_initials',
            field=models.CharField(blank=True, default='GB', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='hd_size_two_initials',
            field=models.CharField(blank=True, default='GB', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='database_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tamanho do Banco'),
        ),
    ]
