# Generated by Django 2.2.2 on 2020-12-08 18:48

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_auto_20201208_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='memory_ram_initials',
            field=models.CharField(blank=True, default='GB', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='servers',
            name='virtual_machine',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Máquina Virtual(S/N)'),
        ),
        migrations.AlterField(
            model_name='information',
            name='last_verification',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 8), null=True, verbose_name='Última Verificação'),
        ),
        migrations.AlterField(
            model_name='information',
            name='server',
            field=models.ForeignKey(on_delete=True, related_name='server_info', to='servers.Servers', verbose_name='Servidor'),
        ),
        migrations.AlterField(
            model_name='information',
            name='user_verification',
            field=models.ForeignKey(default=1, on_delete=False, related_name='user_information', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
    ]
