# Generated by Django 2.2.2 on 2020-12-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_auto_20201208_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='machine_type',
            field=models.CharField(choices=[('Produção', 'Produção'), ('Contingência', 'Contingência'), ('Outros', 'Outros')], default='Produção', max_length=20, verbose_name='Tipo de Máquina'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='memory_ram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RAM(GB)'),
        ),
    ]
