# Generated by Django 2.2.2 on 2020-12-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0011_auto_20201208_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servers',
            options={'ordering': ['companie__nickname', 'machine_type', 'ip_network'], 'verbose_name': 'Servidor', 'verbose_name_plural': 'Servidores'},
        ),
        migrations.AlterField(
            model_name='information',
            name='database_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name do Banco'),
        ),
    ]
