# Generated by Django 2.2.2 on 2020-12-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_auto_20201208_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='database_name',
            field=models.CharField(blank=True, default='X', max_length=50, null=True, verbose_name='Name do Banco'),
        ),
    ]
