# Generated by Django 2.2.2 on 2020-12-09 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0013_auto_20201208_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['server__servers__companie__nickname', 'server__servers__machine_type', 'server__servers__ip_network', '-last_verification'], 'verbose_name': 'Servidor - Informações', 'verbose_name_plural': 'Servidores - Informações'},
        ),
        migrations.AlterModelOptions(
            name='servers',
            options={'ordering': ['companie__nickname', 'machine_type', 'ip_network'], 'verbose_name': 'Servidor - Cadastro', 'verbose_name_plural': 'Servidores - Cadastros'},
        ),
        migrations.AddField(
            model_name='servers',
            name='date_acquisition',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Compra'),
        ),
        migrations.AddField(
            model_name='servers',
            name='provider_acquisition',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Forncedor da Compra'),
        ),
        migrations.AlterField(
            model_name='information',
            name='database_name',
            field=models.CharField(blank=True, default='.', max_length=50, null=True, verbose_name='Name do Banco'),
        ),
        migrations.AlterField(
            model_name='information',
            name='last_verification',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 9), null=True, verbose_name='Última Verificação'),
        ),
    ]
