# Generated by Django 2.2.2 on 2020-12-10 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0014_auto_20201209_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='database_size_initials',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('GB', 'GB'), ('TB', 'TB')], default='GB', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='last_verification',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 10), null=True, verbose_name='Última Verificação'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='provider_acquisition',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fornecedor do Equipamento'),
        ),
    ]
