# Generated by Django 2.2.2 on 2020-12-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0016_auto_20201210_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='hd_size_one',
            field=models.FloatField(blank=True, null=True, verbose_name='Tam/Disco(SO)'),
        ),
        migrations.AlterField(
            model_name='information',
            name='hd_size_one_available',
            field=models.FloatField(blank=True, null=True, verbose_name='Tam/Disco Disp(SO)'),
        ),
        migrations.AlterField(
            model_name='information',
            name='hd_size_two',
            field=models.FloatField(blank=True, null=True, verbose_name='Tam. Disco(BD)'),
        ),
        migrations.AlterField(
            model_name='information',
            name='hd_size_two_available',
            field=models.FloatField(blank=True, null=True, verbose_name='Tam/Disc Disp(BD)'),
        ),
    ]
