# Generated by Django 2.2.2 on 2020-12-21 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0019_auto_20201221_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='last_verification',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 21, 13, 27, 20, 601222, tzinfo=utc), null=True, verbose_name='Última Verificação'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='last_verification',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 21, 13, 27, 20, 600421, tzinfo=utc), null=True, verbose_name='Última Verificação'),
        ),
    ]
