# Generated by Django 2.2.2 on 2020-12-21 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0020_auto_20201221_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='last_verification',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Última Verificação'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='last_verification',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Última Verificação'),
        ),
    ]
