# Generated by Django 2.2.2 on 2020-12-04 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo(S/N)'),
        ),
        migrations.AddField(
            model_name='companies',
            name='cep',
            field=models.CharField(default=1, max_length=9, verbose_name='Cep'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='city',
            field=models.CharField(default=1, max_length=50, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='cnpj',
            field=models.CharField(default=1, max_length=20, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='create',
            field=models.DateField(default=datetime.date.today, verbose_name='Cadastro'),
        ),
        migrations.AddField(
            model_name='companies',
            name='district',
            field=models.CharField(default=1, max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='companies',
            name='fundation',
            field=models.DateField(blank=True, null=True, verbose_name='Fundação'),
        ),
        migrations.AddField(
            model_name='companies',
            name='ie',
            field=models.CharField(default=1, max_length=20, verbose_name='IE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='nickname',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Apelido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='companies',
            name='owner',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Proprietário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='owner_phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Fone Proprietário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='phone_one',
            field=models.CharField(default=1, max_length=20, verbose_name='Fone 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='phone_three',
            field=models.CharField(default=1, max_length=20, verbose_name='Fone 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='phone_two',
            field=models.CharField(default=1, max_length=20, verbose_name='Fone 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='state',
            field=models.CharField(max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='companies',
            name='street',
            field=models.CharField(default=1, max_length=150, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='stret_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Empresa'),
        ),
    ]
