# Generated by Django 2.2.2 on 2020-12-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20201204_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='Proprietário'),
        ),
    ]
