# Generated by Django 2.2.2 on 2020-12-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companies_id_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='create',
            new_name='create_add',
        ),
    ]
