# Generated by Django 2.2.2 on 2020-12-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20201204_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='nickname',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Apelido'),
        ),
    ]
