# Generated by Django 2.2.2 on 2020-12-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20201223_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Empresa'),
        ),
    ]
