# Generated by Django 2.2.2 on 2020-12-21 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Módulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Atualizada')),
                ('date_update', models.DateField(auto_now=True, null=True, verbose_name='Emissão')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'ordering': ['name'],
            },
        ),
    ]
