# Generated by Django 2.2.2 on 2020-12-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20201221_1142'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systems',
            name='module',
            field=models.ForeignKey(default=1, on_delete=False, related_name='module_system', to='modules.Modules', verbose_name='Módulo'),
            preserve_default=False,
        ),
    ]
